# Usar una imagen base de Node.js
FROM node:20-alpine3.21

# Establecer el directorio de trabajo dentro del contenedor
WORKDIR /usr/src/app

# Copiar los archivos de tu proyecto al contenedor
COPY package*.json ./
COPY server.js ./

# Instalar las dependencias
RUN npm install

# Exponer el puerto en el que correrá tu aplicación
EXPOSE 3000

# Comando para iniciar la aplicación
CMD ["node", "server.js"]
